# Generated by Django 5.1.6 on 2025-03-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
